(function (AT) {
  const { content, tr, escape, fmtDate, fmtNumber, fmtMoney, json, status, stat, pageHead, empty, loading, toast, api, body, formJson, parsePairs, setHash, route } = AT;

  AT.views.analytics = async function analyticsView() {
    loading();
    const dimension = route().query.get("dimension") || "project";
    const [breakdown, budgetBody, alertBody] = await Promise.all([
      api(`/analytics/breakdown?dimension=${encodeURIComponent(dimension)}&days=30`),
      api("/analytics/budgets"), api("/analytics/alerts")
    ]);
    const maxTokens = Math.max(1, ...breakdown.groups.map(group => group.totalTokens || 0));
    content.innerHTML = pageHead(tr("多维洞察", "MULTIDIMENSIONAL INSIGHTS"), tr("分析与预算", "Analytics & budgets"), tr("按业务维度聚合质量、Token 和成本，并设置本地预算护栏。", "Aggregate quality, tokens, and cost by business dimension and configure local guardrails.")) + `
      <div class="toolbar">${["project", "environment", "model", "source"].map(item => `<button class="button ${item === dimension ? "primary" : ""} dimension" data-value="${item}">${labelDimension(item)}</button>`).join("")}</div>
      ${alertBody.alerts.length ? `<section class="card"><div class="card-head"><h2 style="color:var(--danger)">${tr("预算告警", "Budget alerts")}</h2></div><div>${alertBody.alerts.map(alert => `<div class="list-item"><strong>${escape(alert.budgetName)}</strong><div class="muted tiny">${escape(alert.value)} · ${escape(alert.metric)} · ${fmtNumber(alert.actual, 3)} / ${fmtNumber(alert.limit, 3)} (${fmtNumber(alert.ratio * 100, 1)}%)</div></div>`).join("")}</div></section>` : ""}
      <div class="grid sidebar" style="margin-top:16px">
        <section class="card"><div class="card-head"><h2>${tr("新建预算", "New budget")}</h2></div><div class="card-body"><form id="budget-form" class="form-grid">
          ${field("name", tr("名称", "Name"), "", true)}
          <label class="field">${tr("维度", "Dimension")}<select class="control" name="dimension">${["project", "environment", "model", "source"].map(item => `<option value="${item}">${labelDimension(item)}</option>`).join("")}</select></label>
          ${field("value", tr("维度值", "Dimension value"), "", true)}
          <label class="field">${tr("周期", "Period")}<select class="control" name="period"><option value="daily">${tr("每日", "Daily")}</option><option value="monthly">${tr("每月", "Monthly")}</option></select></label>
          ${field("maxCostUsd", tr("最大成本 USD", "Max cost USD"), "", false, "number")}${field("maxTokens", tr("最大 Token", "Max tokens"), "", false, "number")}${field("maxRuns", tr("最大 Run", "Max runs"), "", false, "number")}
          <div class="form-actions"><button class="button primary" type="submit">${tr("创建预算", "Create budget")}</button></div>
        </form></div></section>
        <section class="card"><div class="card-head"><h2>${labelDimension(dimension)} · 30 ${tr("天", "days")}</h2></div><div class="table-wrap">${breakdown.groups.length ? `<table><thead><tr><th>${tr("值", "Value")}</th><th>Run</th><th>${tr("失败率", "Failure rate")}</th><th>Token</th><th>${tr("成本", "Cost")}</th></tr></thead><tbody>${breakdown.groups.map(group => `<tr><td><strong>${escape(group.key)}</strong><div class="bar" style="margin-top:6px"><span style="width:${Math.max(2, group.totalTokens / maxTokens * 100)}%"></span></div></td><td>${group.runCount}</td><td>${fmtNumber(group.failureRate * 100, 1)}%</td><td>${fmtNumber(group.totalTokens)}</td><td>${fmtMoney(group.costUsd)}</td></tr>`).join("")}</tbody></table>` : empty(tr("暂无聚合数据。", "No aggregate data."))}</div></section>
      </div>
      <section class="card" style="margin-top:16px"><div class="card-head"><h2>${tr("预算规则", "Budget rules")}</h2></div><div class="table-wrap">${budgetBody.budgets.length ? `<table><thead><tr><th>${tr("名称", "Name")}</th><th>${tr("范围", "Scope")}</th><th>${tr("周期", "Period")}</th><th>${tr("限制", "Limits")}</th><th></th></tr></thead><tbody>${budgetBody.budgets.map(item => `<tr><td>${escape(item.name)}</td><td>${escape(item.dimension)}:${escape(item.value)}</td><td>${escape(item.period)}</td><td>${item.maxCostUsd != null ? fmtMoney(item.maxCostUsd) : ""} ${item.maxTokens != null ? fmtNumber(item.maxTokens) + " tok" : ""} ${item.maxRuns != null ? item.maxRuns + " runs" : ""}</td><td><button class="button small danger delete-budget" data-id="${escape(item.id)}">${tr("删除", "Delete")}</button></td></tr>`).join("")}</tbody></table>` : empty(tr("尚无预算规则。", "No budget rules."))}</div></section>`;
    document.querySelectorAll(".dimension").forEach(button => button.addEventListener("click", () => setHash(`/analytics?dimension=${button.dataset.value}`)));
    document.querySelector("#budget-form").addEventListener("submit", async event => {
      event.preventDefault(); const values = formJson(event.currentTarget);
      await api("/analytics/budgets", { method: "POST", body: body({ name: values.name, dimension: values.dimension, value: values.value, period: values.period, maxCostUsd: optionalNumber(values.maxCostUsd), maxTokens: optionalNumber(values.maxTokens), maxRuns: optionalNumber(values.maxRuns), enabled: true }) });
      toast(tr("预算已创建", "Budget created")); analyticsView();
    });
    document.querySelectorAll(".delete-budget").forEach(button => button.addEventListener("click", async () => { await api(`/analytics/budgets/${encodeURIComponent(button.dataset.id)}`, { method: "DELETE" }); toast(tr("预算已删除", "Budget deleted")); analyticsView(); }));
  };
  function labelDimension(value) { return ({ project: tr("项目", "Project"), environment: tr("环境", "Environment"), model: tr("模型", "Model"), source: tr("来源", "Source") })[value] || value; }
  function optionalNumber(value) { return value === "" || value == null ? undefined : Number(value); }
  function field(name, label, value = "", required = false, type = "text") { return `<label class="field">${escape(label)}<input class="control" type="${type}" name="${name}" value="${escape(value)}" ${required ? "required" : ""}></label>`; }

  AT.views.evaluations = async function evaluationsView() {
    loading(); const selectedId = route().query.get("dataset");
    const datasetsBody = await api("/evaluations/datasets");
    const report = selectedId ? await api(`/evaluations/datasets/${encodeURIComponent(selectedId)}`) : null;
    content.innerHTML = pageHead(tr("质量回归", "QUALITY REGRESSION"), tr("Agent 评测集", "Agent evaluations"), tr("管理回归用例，并将 Run 评分为可比较的质量指标。", "Manage regression cases and score Runs with comparable quality metrics.")) + `
      <div class="grid sidebar">
        <div><section class="card"><div class="card-head"><h2>${tr("新建评测集", "New dataset")}</h2></div><div class="card-body"><form id="dataset-form" class="form-grid">${field("name", tr("名称", "Name"), "", true)}${field("scoreWeights", tr("评分权重", "Score weights"), "correctness:0.7,efficiency:0.3", true)}<label class="field full">${tr("说明", "Description")}<textarea class="control" name="description"></textarea></label><div class="form-actions"><button class="button primary">${tr("创建", "Create")}</button></div></form></div></section>
          <section class="card"><div class="card-head"><h2>${tr("评测集", "Datasets")}</h2></div><div class="list">${datasetsBody.datasets.length ? datasetsBody.datasets.map(dataset => `<a class="list-item selectable ${dataset.id === selectedId ? "selected" : ""}" href="#/evaluations?dataset=${encodeURIComponent(dataset.id)}"><strong>${escape(dataset.name)}</strong><div class="muted tiny">${dataset.caseCount} cases · ${dataset.resultCount} results · ${fmtNumber(dataset.averageQualityScore * 100, 1)}</div></a>`).join("") : empty(tr("尚无评测集。", "No datasets."))}</div></section></div>
        <section class="card"><div class="card-head"><h2>${report ? escape(report.dataset.name) : tr("评测详情", "Evaluation details")}</h2>${report ? `<strong class="mono">${fmtNumber(report.dataset.averageQualityScore * 100, 1)}</strong>` : ""}</div><div class="card-body">${report ? evaluationReport(report) : empty(tr("选择一个评测集查看用例和评分。", "Select a dataset to inspect cases and scores."))}</div></section>
      </div>`;
    document.querySelector("#dataset-form").addEventListener("submit", async event => { event.preventDefault(); const values = formJson(event.currentTarget); const created = await api("/evaluations/datasets", { method: "POST", body: body({ name: values.name, description: values.description || undefined, scoreWeights: parsePairs(values.scoreWeights) }) }); toast(tr("评测集已创建", "Dataset created")); setHash(`/evaluations?dataset=${encodeURIComponent(created.id)}`); });
    if (report) wireEvaluationForms(report.dataset.id);
  };
  function evaluationReport(report) {
    return `<div class="grid two"><form id="case-form" class="form-grid">${field("name", tr("用例名称", "Case name"), "", true)}<label class="field full">${tr("输入 JSON", "Input JSON")}<textarea class="control mono" name="input" required>{}</textarea></label><label class="field full">${tr("期望输出 JSON", "Expected output JSON")}<textarea class="control mono" name="expectedOutput"></textarea></label><div class="form-actions"><button class="button primary">${tr("添加用例", "Add case")}</button></div></form>
      <form id="score-form" class="form-grid"><label class="field">${tr("用例", "Case")}<select class="control" name="caseId" required>${report.cases.map(item => `<option value="${escape(item.id)}">${escape(item.name)}</option>`).join("")}</select></label>${field("runId", "Run ID", "", true)}${field("scores", tr("评分", "Scores"), "correctness:0.8,efficiency:0.6", true)}${field("notes", tr("备注", "Notes"))}<div class="form-actions"><button class="button primary" ${report.cases.length ? "" : "disabled"}>${tr("保存评分", "Save score")}</button></div></form></div>
      <div class="list" style="margin-top:18px;border:1px solid var(--border);border-radius:9px">${report.cases.length ? report.cases.map(item => `<div class="list-item"><strong>${escape(item.name)}</strong><div class="muted tiny mono">${escape(JSON.stringify(item.input))}</div>${item.results.map(result => `<div style="display:flex;justify-content:space-between;margin-top:8px;padding:8px;background:var(--surface-2);border-radius:6px"><span class="mono tiny">${escape(result.runId)}</span><strong>${fmtNumber(result.qualityScore * 100, 1)}</strong></div>`).join("")}</div>`).join("") : empty(tr("尚无用例。", "No cases."))}</div>`;
  }
  function wireEvaluationForms(datasetId) {
    document.querySelector("#case-form").addEventListener("submit", async event => { event.preventDefault(); const values = formJson(event.currentTarget); await api(`/evaluations/datasets/${encodeURIComponent(datasetId)}/cases`, { method: "POST", body: body({ name: values.name, input: JSON.parse(values.input), expectedOutput: values.expectedOutput ? JSON.parse(values.expectedOutput) : undefined }) }); toast(tr("用例已添加", "Case added")); AT.views.evaluations(); });
    document.querySelector("#score-form").addEventListener("submit", async event => { event.preventDefault(); const values = formJson(event.currentTarget); await api("/evaluations/results", { method: "POST", body: body({ caseId: values.caseId, runId: values.runId, scores: parsePairs(values.scores), notes: values.notes || undefined }) }); toast(tr("评分已保存", "Score saved")); AT.views.evaluations(); });
  }

  AT.views.sandbox = async function sandboxView() {
    loading();
    const current = route(); const runId = current.query.get("runId") || ""; const requestedEventId = current.query.get("eventId") || "";
    const encodedRun = encodeURIComponent(runId);
    const [tasksBody, sourceRun, sourceEvents] = await Promise.all([
      api(`/sandbox/replays?limit=100${runId ? `&sourceRunId=${encodedRun}` : ""}`),
      runId ? api(`/runs/${encodedRun}`).catch(() => null) : null,
      runId ? api(`/runs/${encodedRun}/events?legacy=1`).catch(() => []) : []
    ]);
    const selectedEvent = sourceEvents.find(event => event.id === requestedEventId) || sourceEvents[0];
    content.innerHTML = pageHead(tr("安全实验", "SAFE EXPERIMENTS"), tr("Mock 回放沙箱", "Mock replay sandbox"), tr("在无网络、无真实工具副作用的环境中重放事件输入。", "Replay event inputs without network access or real tool side effects."), `<button class="button" id="sandbox-refresh">${tr("刷新", "Refresh")}</button>`) + `
      <div class="stats">${stat(tr("网络", "Network"), tr("禁用", "Disabled"))}${stat(tr("工具执行", "Tool execution"), "Mock only")}${stat(tr("文件系统", "Filesystem"), tr("临时", "Temporary"))}${stat(tr("任务", "Tasks"), tasksBody.tasks.length)}</div>
      <section class="card"><div class="card-head"><h2>${tr("载入来源 Run", "Load source Run")}</h2></div><div class="card-body"><form id="load-run-form" class="toolbar"><input class="control grow mono" name="runId" value="${escape(runId)}" required placeholder="run-id"><button class="button">${tr("载入", "Load")}</button>${sourceRun ? `<a class="button" href="#/runs/${encodedRun}">${tr("查看详情", "View details")}</a>` : ""}</form>${runId && !sourceRun ? `<div class="error-box">${tr("未找到该 Run。", "Run not found.")}</div>` : ""}${sourceRun ? `<div class="muted tiny">${escape(sourceRun.name)} · ${sourceEvents.length} ${tr("个事件", "events")}</div>` : ""}</div></section>
      <div class="grid sidebar"><section class="card"><div class="card-head"><h2>${tr("创建回放", "Create replay")}</h2></div><div class="card-body"><form id="replay-form" class="form-grid">
        <input type="hidden" name="sourceRunId" value="${escape(runId)}">${sourceEvents.length ? `<label class="field full">${tr("来源事件", "Source event")}<select class="control" name="sourceEventId" required>${sourceEvents.map(event => `<option value="${escape(event.id)}" ${event.id === selectedEvent?.id ? "selected" : ""}>${escape(event.type)} · ${escape(event.name)} · ${escape(event.id)}</option>`).join("")}</select></label>` : field("sourceEventId", tr("来源 Event ID", "Source Event ID"), requestedEventId, true)}
        <label class="field full">${tr("覆盖输入 JSON（可选）", "Override input JSON (optional)")}<textarea class="control mono" name="input" placeholder='${escape(JSON.stringify(selectedEvent?.input ?? {}))}'></textarea></label><label class="field full">${tr("Mock 输出 JSON（可选）", "Mock output JSON (optional)")}<textarea class="control mono" name="mockOutput"></textarea></label>
        ${field("delayMs", tr("延迟 ms", "Delay ms"), "0", false, "number")}${field("timeoutMs", tr("超时 ms", "Timeout ms"), "5000", false, "number")}
        <label class="field"><span><input type="checkbox" name="simulateError"> ${tr("模拟失败", "Simulate error")}</span></label><div class="form-actions"><button class="button primary" ${runId ? "" : "disabled"}>${tr("启动回放", "Start replay")}</button></div>
      </form></div></section>
      <section class="card"><div class="card-head"><h2>${tr("回放任务", "Replay tasks")}</h2></div><div class="list">${tasksBody.tasks.length ? tasksBody.tasks.map(task => `<div class="list-item"><div style="display:flex;justify-content:space-between;gap:12px"><div><strong class="mono tiny">${escape(task.id)}</strong><div class="muted tiny">${escape(task.sourceRunId)} · ${escape(task.sourceEventId)} · ${fmtDate(task.createdAt)}</div></div>${status(task.status)}</div>${task.replayRunId ? `<div class="section-actions" style="margin-top:9px"><a class="button small" href="#/runs/${encodeURIComponent(task.replayRunId)}">${tr("查看生成 Run", "View replay Run")}</a><a class="button small" href="#/runs/compare?ids=${encodeURIComponent(`${task.sourceRunId},${task.replayRunId}`)}">${tr("对比", "Compare")}</a></div>` : ""}${["queued", "running"].includes(task.status) ? `<button class="button small danger cancel-replay" data-id="${escape(task.id)}" style="margin-top:9px">${tr("取消", "Cancel")}</button>` : ""}${task.error ? `<div class="muted tiny" style="color:var(--danger);margin-top:7px">${escape(task.error)}</div>` : ""}</div>`).join("") : empty(tr("尚无回放任务。", "No replay tasks."))}</div></section></div>`;
    document.querySelector("#sandbox-refresh").addEventListener("click", sandboxView);
    document.querySelector("#load-run-form").addEventListener("submit", event => { event.preventDefault(); const values = formJson(event.currentTarget); setHash(`/sandbox?runId=${encodeURIComponent(values.runId)}`); });
    document.querySelector("#replay-form").sourceEventId?.addEventListener("change", event => setHash(`/sandbox?runId=${encodedRun}&eventId=${encodeURIComponent(event.target.value)}`));
    document.querySelector("#replay-form").addEventListener("submit", async event => { event.preventDefault(); const values = formJson(event.currentTarget); await api("/sandbox/replays", { method: "POST", body: body({ sourceRunId: values.sourceRunId, sourceEventId: values.sourceEventId, input: values.input ? JSON.parse(values.input) : undefined, mockOutput: values.mockOutput ? JSON.parse(values.mockOutput) : undefined, simulateError: event.currentTarget.simulateError.checked, delayMs: Number(values.delayMs || 0), timeoutMs: Number(values.timeoutMs || 5000) }) }); toast(tr("回放任务已创建", "Replay created")); sandboxView(); });
    document.querySelectorAll(".cancel-replay").forEach(button => button.addEventListener("click", async () => { await api(`/sandbox/replays/${encodeURIComponent(button.dataset.id)}`, { method: "DELETE" }); toast(tr("任务已取消", "Replay cancelled")); sandboxView(); }));
  };

  AT.views.maintenance = async function maintenanceView() {
    loading(); const [stats, tombstoneBody, privacy] = await Promise.all([api("/maintenance/storage"), api("/maintenance/tombstones?limit=50"), api("/maintenance/privacy")]);
    content.innerHTML = pageHead(tr("本地治理", "LOCAL GOVERNANCE"), tr("维护与隐私控制中心", "Maintenance & privacy"), tr("管理 SQLite 容量、保留期、删除墓碑与写入前字段脱敏。", "Manage SQLite capacity, retention, tombstones, and pre-storage redaction."), `<button class="button" id="compact-db">${tr("压缩数据库", "Compact database")}</button>`) + `
      <div class="stats">${stat("Run", fmtNumber(stats.runs))}${stat("Event", fmtNumber(stats.events))}${stat("Usage Session", fmtNumber(stats.usageSessions))}${stat(tr("数据库", "Database"), formatBytes(stats.databaseBytes))}${stat(tr("墓碑", "Tombstones"), fmtNumber(stats.tombstones))}</div>
      <section class="card"><div class="card-head"><h2>${tr("数据库位置", "Database location")}</h2></div><div class="card-body mono tiny">${escape(stats.databasePath)}</div></section>
      <div class="grid two" style="margin-top:16px"><section class="card"><div class="card-head"><h2>${tr("写入前脱敏", "Pre-storage redaction")}</h2></div><div class="card-body"><form id="privacy-form"><label class="field">${tr("敏感字段（逗号或换行）", "Sensitive keys (comma or newline)")}<textarea class="control" name="sensitiveKeys">${escape((privacy.sensitiveKeys || []).join("\n"))}</textarea></label>${field("replacement", tr("替换文本", "Replacement"), privacy.replacement || "[REDACTED]", true)}<div class="form-actions"><button class="button primary">${tr("保存规则", "Save rules")}</button></div></form></div></section>
      <section class="card"><div class="card-head"><h2>${tr("按日期清理", "Prune by date")}</h2></div><div class="card-body"><form id="prune-form">${field("before", tr("删除此日期之前", "Delete before"), new Date(Date.now() - 90 * 86400000).toISOString().slice(0, 10), true, "date")}<div class="form-actions"><label class="tiny"><input type="checkbox" name="success" checked> success</label><label class="tiny"><input type="checkbox" name="error" checked> error</label><label class="tiny"><input type="checkbox" name="keepTombstones" checked> ${tr("保留墓碑", "Keep tombstones")}</label></div><div class="form-actions"><button class="button danger">${tr("执行清理", "Prune runs")}</button></div></form></div></section></div>
      <section class="card" style="margin-top:16px"><div class="card-head"><h2>${tr("最近删除", "Recently deleted")}</h2></div><div class="table-wrap">${tombstoneBody.tombstones.length ? `<table><thead><tr><th>Run ID</th><th>${tr("删除时间", "Deleted")}</th><th>${tr("原因", "Reason")}</th><th></th></tr></thead><tbody>${tombstoneBody.tombstones.map(item => `<tr><td class="mono">${escape(item.runId)}</td><td>${fmtDate(item.deletedAt)}</td><td>${escape(item.reason || "—")}</td><td><button class="button small restore-run" data-id="${escape(item.runId)}">${tr("解除墓碑", "Restore ID")}</button></td></tr>`).join("")}</tbody></table>` : empty(tr("没有删除墓碑。", "No tombstones."))}</div></section>`;
    document.querySelector("#compact-db").addEventListener("click", async () => { await api("/maintenance/compact", { method: "POST", body: body({}) }); toast(tr("数据库已压缩", "Database compacted")); maintenanceView(); });
    document.querySelector("#privacy-form").addEventListener("submit", async event => { event.preventDefault(); const values = formJson(event.currentTarget); await api("/maintenance/privacy", { method: "PUT", body: body({ sensitiveKeys: values.sensitiveKeys.split(/[\n,]/).map(item => item.trim()).filter(Boolean), replacement: values.replacement || "[REDACTED]" }) }); toast(tr("隐私规则已保存", "Privacy rules saved")); maintenanceView(); });
    document.querySelector("#prune-form").addEventListener("submit", async event => { event.preventDefault(); if (!confirm(tr("确定执行清理？", "Run retention cleanup?"))) return; const form = event.currentTarget; const statuses = [form.success.checked ? "success" : null, form.error.checked ? "error" : null].filter(Boolean); const result = await api("/maintenance/prune", { method: "POST", body: body({ before: new Date(`${form.before.value}T00:00:00.000Z`).toISOString(), statuses, keepTombstones: form.keepTombstones.checked }) }); toast(`${tr("已删除", "Deleted")} ${result.deleted} Runs`); maintenanceView(); });
    document.querySelectorAll(".restore-run").forEach(button => button.addEventListener("click", async () => { await api(`/runs/${encodeURIComponent(button.dataset.id)}/tombstone`, { method: "DELETE" }); toast(tr("Run ID 已恢复", "Run ID restored")); maintenanceView(); }));
  };
  function formatBytes(value) { const bytes = Number(value || 0); if (bytes < 1024) return `${bytes} B`; if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KiB`; return `${(bytes / 1048576).toFixed(1)} MiB`; }
})(window.AT);
